apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-toolkit
  labels:
    app: dev-toolkit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev-toolkit
  template:
    metadata:
      labels:
        app: dev-toolkit
    spec:
      containers:
        - name: ubuntu
          image: registry.cn-hangzhou.aliyuncs.com/c137/ubuntu-dev:latest
          imagePullPolicy: Always
          tty: true
          command:
            - zsh
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
        - name: busybox
          image: busybox:1.28
          tty: true
          command:
            - sh
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
