apiVersion: v1
kind: Pod
metadata:
  name: devtools
spec:
  containers:
    - name: ubuntu
      image: registry.cn-hangzhou.aliyuncs.com/private_ns/ubuntu-dev
      tty: true
      command:
        - zsh
      resources:
        limits:
          cpu: "2"
          memory: "1Gi"
    - name: busybox
      image: busybox:1.33.1
      tty: true
      command:
        - bash
      resources:
        limits:
          cpu: "1"
          memory: "1Gi"
