apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
spec:
  containers:
    - name: ubuntu
      image: registry.cn-hangzhou.aliyuncs.com/private_ns/ubuntu-dev
      tty: true
      command:
        - zsh
      resources:
        limits:
          cpu: "2"
          memory: "1Gi"
